server:
  port: 8002

spring:
  application:
    name: config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/MRSTK90/galaxy-config-repository
          default-label: main


